### ISSUE TITLE
Turn getGlobalThis() into a constant

### ISSUE THREAD

**Issue by jdalton** [caridy/secure-javascript-environment#20]
I noticed this function will modify `Object.prototype` whenever it is called (if `globalThis` is not available). Can this be turned into a constant instead of a function so that it's done once?

**Comment by jdalton** [comment]
Related source note:
https://github.com/caridy/secure-javascript-environment/blob/1234af80ebe0af6038f3f90ec936f7ac7d3da052/src/shared.ts#L140-L141

**Comment by caridy** [comment]
The only reason for this to be there is because some env do not have `globalThis` yet... we can probably drop this at some point.

**Comment by caridy** [comment]
fixed by https://github.com/caridy/secure-javascript-environment/commit/bd9ad05cec6fb0a2be74c3e575da678d836eefaf#diff-8de5f1f9c50c1fe9f3a6d8b6cd1daeebL159
