### ISSUE TITLE
ConsoleInfo and ConsoleError

### ISSUE THREAD

**Issue by jdalton** [caridy/secure-javascript-environment#27]
We should pluck the `console.info` and `console.error` methods off as `ConsoleInfo` and `ConsoleError`. Previous versions of `console` needed them bound so we can bind them:
```js
const bind = uncurry(Function.prototype.bind);
const ConsoleError = bind(console.error, console);
const ConsoleInfo = bind(console.info, console);
```
or if we only bind them there and don't need the helper anywhere else
```js
const ConsoleError = console.error.bind(console);
const ConsoleInfo = console.info.bind(console);
```

**Comment by caridy** [comment]
hmm, what is the problem with console.*? it is not currently defined by the new realm, it is piped through the membrane, which makes it kinda immune to the inner realm to mess with.

**Comment by jdalton** [comment]
Ah yes! I forgot it wasn't of the shadow realm.
