### ISSUE TITLE
Is the removal of the iframe from the document sufficiently stable?

### ISSUE THREAD

**Issue by caridy** [caridy/secure-javascript-environment#32]
@jfparadis and @erights raised this issue during the SES meeting based on some previous conversations around this topic with some implementers. Specifically, he recalled some concerns from @littledan about this.

We should validate that indeed this is stable enough to rely on the intrinsics.

**Comment by littledan** [comment]
I thought that even if you remove an iframe from the document, it still has a global object. (I did not verify this, though.) Is this what you are talking about?

**Comment by caridy** [comment]
Yes, from what we can tell, the detached iframe has a good global object, and all the intrinsics are working fine, but it fails if you touch anything that requires host cooperation, e.g.: `import('/something')`

**Comment by littledan** [comment]
I think these sorts of things are defined by the HTML spec (and I'm not really an HTML expert). Are you just wondering about `import()` only, or also about which other APIs?

**Comment by caridy** [comment]
The `import()` we know exactly why it fails (which btw it is great for what we are doing), it fails because the host keeps the registry of modules, and does the fetch routine. We are wondering about other potential issues with the stability of the global object and the intrinsics there.

**Comment by littledan** [comment]
Sorry, I am not a DOM expert, so I can't give you a complete answer. Maybe try asking in #whatwg on Freenode IRC.

**Comment by caridy** [comment]
closing in favor of #52 and #53, the rest seems to be stable.
