### ISSUE TITLE
Is an already imported module importable from within the disconnected iframe? 

### ISSUE THREAD

**Issue by caridy** [caridy/secure-javascript-environment#33]
This is another question from SES meeting. If the disconnected iframe imports one module over the network before it is disconnected, can the disconnected iframe access that module again?

The only way to import a module (again) is via a dynamic `import`, which could be done via `eval()` as follow:

```js
eval(`import('./same/path.js')`);
```

**Comment by caridy** [comment]
My assumption here is that it does not work because ecma262 specifies that the registry of the modules is something controlled by the host, and the language doesn't do any cache. Now, that guarantees nothing because implementers might be doing some optimizations under the hood, so it might very well be available.

As for whether or not this is important for some of us, it is certainly not important for my use-cases because we can simply avoid loading anything before the removal, and in fact in this package is it removed synchronously without loading anything, but this is an interesting question nevertheless.

**Comment by jdalton** [comment]
Tested in Chrome and a previously loaded module is still rejected when the iframe is detached since it no-longer has the browser context it did when the loaded module was fetched (before detaching)

**Comment by caridy** [comment]
Excellent, thanks @jdalton
