### ISSUE TITLE
[browser bug] chrome issue with custom elements from another realm

### ISSUE THREAD

**Issue by caridy** [caridy/secure-javascript-environment#52]
When a new component is defined in another realm, and registered in the main window, it fails to be created via innerHTML and `document.createElement` but works fine via `new` on the defined class.

Chromium Tracker:
https://bugs.chromium.org/p/chromium/issues/detail?id=1042435

**Comment by caridy** [comment]
@jdalton can you follow up on this issue? maybe opening an issue for chromium? The simplified example https://github.com/caridy/secure-javascript-environment/commit/7ed0513be6927c39a00ee19b46c7e0d34166c519 seems to be failing consistency for me, and the full example (in examples/custom-elements.html) is failing as well, it was working fine before IIRC.

**Comment by jdalton** [comment]
Thanks, followed up with issue (added in issue description) 😸

**Comment by jdalton** [comment]
Fixed by #55.
