### ISSUE TITLE
[investigation] symbols should be remapped

### ISSUE THREAD

**Issue by caridy** [caridy/secure-javascript-environment#60]
As today, symbols are considered primitive, but the following code leaks today:

```js
Symbol().constructor.__proto__ === Function.prototype
```

based on the assumption that we let symbols to pass through the membrane.

and additionally problem to be looked at here is the `Symbol.from()`.

**Comment by mmis1000** [comment]
But call the .contructor property in another realm's function seems return `Function` of given realm? So it may not be a problem.

**Comment by caridy** [comment]
@mmis1000 again, excellent timing since I was planning to solve this issue this week, and turns out it was not an issue after all. I added a bunch of tests in https://github.com/caridy/secure-javascript-environment/commit/850a99985599c4c167ca2213ca51059772d70094 to validate it in all browsers.

Now, I will like to get some feedback on this from @erights, specially because by reading the spec, I could not tell that the behavior that you described is in fact specified in 262. Either I'm not looking on the right place, or this is underspecified.

Nevertheless, it is great that this is not an issue.

**Comment by caridy** [comment]
Just to add to this, here is the full example:

```html
    <script>
    const iframe = document.createElement('iframe');
    document.body.appendChild(iframe);
    const { contentWindow: { eval: iframeEval } } = iframe;
    iframeEval(`
        // all to log `true`
        console.log(Symbol().constructor.__proto__ === Function.prototype);
        console.log(Symbol().constructor.__proto__.constructor('return this')() === globalThis);
        console.log(top.Symbol().constructor === Symbol().constructor);
        console.log(top.Symbol().constructor.__proto__ === Function.prototype);
        console.log(top.Symbol().constructor.__proto__.constructor('return this')() === globalThis);
    `);
    </script>
```
