### ISSUE TITLE
apply vs call to avoid the creation of the extra array in `installLazyGlobals`

### ISSUE THREAD

**Issue by caridy** [caridy/secure-javascript-environment#9]
`const value: any = apply(originalGetter, baseGlobalThis, []);` this one can probably reuse an empty array cached at the module level, but ... `apply(originalSetter, baseGlobalThis, [v]);` is more complicated to solve. @jdalton has some ideas here.

**Comment by jdalton** [comment]
My helper looked like:

```js
const emptyArgs = []

function call(target, thisArg) {
  const { length } = arguments

  if (length < 3) {
    return apply(target, thisArg, emptyArgs)
  }

  let index = 1
  const args = new Array(length - 2)

  while (++index < length) {
    args[index - 2] = arguments[index]
  }

  return apply(target, thisArg, args)
}
```

I eventually sided that it was more trouble, and slower, than it was worth to avoid the throw-away array :p

**Comment by caridy** [comment]
fair enough! closing in favor of https://github.com/caridy/secure-javascript-environment/pull/10, which covers the cases of the empty array, and only one instance creates a new array with one element.
